language: node_js

node_js:
  - "v8.10.0"


env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings

before_script:
  - psql -c 'create database greetings;' -U postgres
  - psql -U postgres -d greetings -a -f table.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
